version: '3'
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SERVERURL=__SERVERIP__
      - SERVERPORT=51820
      - PEERS=20
      - PEERDNS=8.8.8.8
    volumes:
      - __WIREGUARD_CONFIG_DIR__:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
    networks:
      - internal

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://__GITLAB_DOMAIN__'"
    volumes:
      - __GITLAB_CONFIG_DIR__:/etc/gitlab
      - __GITLAB_LOGS_DIR__:/var/log/gitlab
      - __GITLAB_DATA_DIR__:/var/opt/gitlab
    networks:
      - internal

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: __MYSQL_ROOT_PASSWORD__
      MYSQL_DATABASE: __MYSQL_DATABASE__
    volumes:
      - __MYSQL_DATA_DIR__:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: __MYSQL_ROOT_PASSWORD__
    depends_on:
      - mysql
    networks:
      - internal

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=__MYSQL_ROOT_PASSWORD__
    volumes:
      - __NEXTCLOUD_DATA_DIR__:/var/www/html
    depends_on:
      - mysql
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - __NGINX_CONF_DIR__:/etc/nginx/conf.d
      - __NGINX_CERTS_DIR__:/etc/ssl/certs
      - __NGINX_VHOST_DIR__:/etc/nginx/vhost.d
    depends_on:
      - gitlab
      - mysql
      - phpmyadmin
      - nextcloud
    networks:
      - internal

networks:
  internal:
    driver: bridge
