version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://__GITLAB_DOMAIN__'"
    volumes:
      - __GITLAB_CONFIG_DIR__:/etc/gitlab
      - __GITLAB_LOGS_DIR__:/var/log/gitlab
      - __GITLAB_DATA_DIR__:/var/opt/gitlab
    networks:
      - internal

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: __MYSQL_ROOT_PASSWORD__
      MYSQL_DATABASE: __MYSQL_ROOT_DATABASE__
    volumes:
      - __MYSQL_DATA_DIR__:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: __MYSQL_ROOT_PASSWORD__
    depends_on:
      - mysql
    networks:
      - internal

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=__MYSQL_ROOT_PASSWORD__
    volumes:
      - __NEXTCLOUD_DATA_DIR__:/var/www/html
    depends_on:
      - mysql
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - __NGINX_CONF_DIR__:/etc/nginx/conf.d
      - __NGINX_CERTS_DIR__:/etc/ssl/certs
      - __NGINX_VHOST_DIR__:/etc/nginx/vhost.d
      - __NGINX_HTML_DIR__:/usr/share/nginx/html
    depends_on:
      - gitlab
      - mysql
      - phpmyadmin
      - nextcloud
      - certbot
    networks:
      - internal

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - __NGINX_CERTS_DIR__:/etc/letsencrypt
      - __NGINX_VHOST_DIR__:/var/lib/letsencrypt
      - __NGINX_HTML_DIR__:/usr/share/nginx/html
    networks:
      - internal

networks:
  internal:
    driver: bridge
